### ISSUE TITLE
[SOPS] - ADD ABILITY FOR ADDING DECRYPTION

### ISSUE THREAD

**Issue by patrick-hermann-sva** [stuttgart-things/flux2-cluster-bootstrap#3]
# snippet 
```yaml
decryption:
    provider: sops
    secretRef:
      name: sops-age
```

# full example
```yaml
#gotk-sync.yaml
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: flux-system
  namespace: flux-system
spec:
  interval: 10m0s
  path: ./clusters/labul/vsphere/xplane-dev2
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
  decryption:
    provider: sops
    secretRef:
      name: sops-age
```
